datamadsite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('datamad2.urls')),
    path('api/', include('datamad2_api.urls')),
    path('oauth/', include('jira_oauth.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dmp/urls.py
from django.urls import path
from dmp import views

urlpatterns = [
    path('projects', views.project_list, name='project_list'),
    path('project/<int:pk>/', views.project_detail, name='project_detail'),
    path('dataproduct/new/<int:project_id>', views.dataproduct_new, name='dataproduct_new'),
    path('dataproduct/edit/<int:pk>/<int:project_id>', views.dataproduct_edit, name='dataproduct_edit'),
    path('dataproduct/delete/<int:pk>/', views.dataproduct_delete, name='dataproduct_delete'),
    path('dataproduct/<int:pk>/', views.dataproduct_detail, name='dataproduct_detail'),
    path('project/<int:pk>/edit', views.project_edit, name='project_edit')
]

dmp/models.py
from django.db import models
from datamad2.models import MyUser


from datetime import datetime, timedelta, date
from django.contrib.contenttypes.fields import GenericRelation, GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.db.models.fields import PositiveIntegerField

# import users
from django.contrib.auth.models import *

from sizefield.models import FileSizeField


class Person(MyUser):
    class Meta:
        proxy = True
        ordering = ('first_name',)

    def __str__(self):
        return self.first_name + ' ' + self.last_name

class Programme(models.Model):

    # grants have a programme

    title = models.CharField(max_length=200)

    def __str__(self):
        return f"{self.title[:50]}"


class Project(models.Model):

    # Projects are activities under funding programmes that are examined
    # for their data management needs.

    title = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    desc = models.TextField(blank=True, null=True, verbose_name="Description")
    notes = GenericRelation("Note")
    data_activities = models.TextField(blank=True, null=True, help_text="Short description of data generation activities. eg Data will be collected by FAAM aircraft/ground instruments. Are there intensive measurement campaigns?")
    startdate = models.DateField(blank=True, null=True,verbose_name="Start Date",help_text="Date format dd/mm/yyyy")
    enddate = models.DateField(blank=True, null=True,verbose_name="End Date",help_text="Date format dd/mm/yyyy")
    dmp_agreed = models.DateField(blank=True, null=True, verbose_name="DMP Agreed on",help_text="Date format dd/mm/yyyy")
    initial_contact = models.DateField(blank=True, null=True, verbose_name="Initial Contact on",help_text="Date format dd/mm/yyyy")
    sciSupContact = models.ForeignKey(Person, help_text="Data centre contact for this project", blank=True, null=True, on_delete=models.PROTECT)
    sciSupContact2 = models.ForeignKey(Person, help_text="Data centre contact for this project", blank=True, null=True, related_name="sciSupContact2s", on_delete=models.PROTECT)
    PI = models.CharField(max_length=200, blank=True, null=True)
    PIemail = models.EmailField(max_length=200, blank=True, null=True, verbose_name='PI email')
    PIinst = models.CharField(max_length=200, blank=True, null=True)
    Contact1 = models.CharField(max_length=200, blank=True, null=True)
    Contact2 = models.CharField(max_length=200, blank=True, null=True)
    projectcost = models.IntegerField(blank=True, null=True)
    services = models.TextField(blank=True, null=True)
    primary_dataCentre = models.CharField(max_length=200,blank=True, null=True, verbose_name="Primary Data Centre")
    other_dataCentres = models.CharField(max_length=200, blank=True, null=True, verbose_name="Other Data Centres")
    status = models.CharField(max_length=200, blank=True, null=True,
            choices=(("Proposal","Proposal"),
                 ("NotFunded","Not Funded"),
                 ("NotStarted","Not Started"),
                 ("Active","Active"),
                 ("NoData","No Data"),
                 ("EndedWithDataToCome","Ended with data to come"),
                 ("Defaulted","Defaulted"),
                 ("NoDataForUs","No data for us"),
                 ("Complete","Complete"),
                 ("Unresponsive", "Unresponsive"),
                 ("MergedProject/HandledElsewhere", "Merged Project/Handled Elsewhere"),
                     ))
    project_status = models.CharField(max_length=200, blank=True, null=True,
            choices=(("Initial contact", "Initial contact"),
                 ("DMP comms","DMP comms"),
                 ("Progress","Progress"),
                 ("Data delivery", "Data delivery"),
                     ))
    modified = models.DateTimeField(auto_now=True)
    #third_party_data = models.ManyToManyField('DataProduct', related_name='requirements+',
                        #blank=True, null=True)
    # vms = models.ManyToManyField(VM, blank=True, null=True)
    # groupworkspaces = models.ManyToManyField(GWS, blank=True, null=True)
    project_URL = models.URLField(blank=True, null=True)
    dmp_URL = models.URLField(blank=True, null=True, verbose_name="DMP URL")
    ODMP_URL = models.URLField(blank=True,null=True, help_text="Outline DMP URL autogenerated when using grant uploader, essentially a best guess. Edit as necessary.")
    moles_URL = models.URLField(blank=True,null=True)
    helpscout_url = models.URLField(blank=True, null=True, verbose_name="OpMan URL")
    project_usergroup = models.CharField(max_length=200, blank=True, null=True, help_text="Group name for registration for this group")
    #metadata_form = GenericRelation("MetadataForm")
    programme = models.ForeignKey(Programme, blank=True, null=True, on_delete=models.PROTECT )
    reassigned = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.title[:50]}"

    def ndata(self):
        dps = DataProduct.objects.filter(project=self)
        return len(dps)





class DataProduct(models.Model):
    # Data products are data streams produced by projects

    title = models.CharField(max_length=200)
    desc = models.TextField(blank=True, null=True, verbose_name='Description')
    notes = GenericRelation("Note")
    datavol = FileSizeField(default=0, verbose_name='Data Volume')
    project = models.ForeignKey(Project, help_text="Project producing this data", blank=True, null=True, on_delete=models.PROTECT)
    sciSupContact = models.ForeignKey(Person, help_text="Data centre contact for this data", blank=True, null=True, on_delete=models.PROTECT)
    contact1 = models.CharField(max_length=200, blank=True, null=True, verbose_name='Contact 1')
    contact2 = models.CharField(max_length=200, blank=True, null=True, verbose_name='Contact 2')
    deliverydate = models.DateField(blank=True, null=True, verbose_name='Delivery Date')
    preservation_plan = models.CharField(
        max_length=200,
        blank=True,
        null=True,
        choices=(
            ("Reference", "Reference data with principal use to provide evidence for publication"),
            ("Structured", "Structured data with set format and metadata conventions"),
            ("Interoperable", "Interoperable data with formats and metadata conventions for specific community tools"),
            ("InProject", "Data management within the project only. No archive involvement"),
            ("OtherRepositories", "Other Non-NERC repositories"),
            ("BODC", "British Oceanographic Data Centre"),
            ("EIDC", "Environmental Information Data Centre "),
            ("PDC", "Polar Data Centre"),
            ("NGDC", "National Geoscience Data Centre"),
            ("OtherDMP", "This data is planned within another project DMP"),
            ("KeepIndefinitely", "Keep Indefinitely"),
            ("KeepAsIs", "Keep as is - Even if obsolete"),
            ("Dispose5years ", "Review for disposal 5 years after project completes"),
            ("ManageInProject", "Don't Archive - manage the data within the project"),
            ("Subset", "Plan to keep a subset of the data indefinitely"),
            ("TBD", "TBD")
        )
    )
    added = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    review_date = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=200, blank=True, null=True,
                              choices=(("WithProjectTeam", "With Project Team"),
                                       ("Ingesting", "Ingesting"),
                                       ("Archived", "Archived and complete"),
                                       ("Defaulted", "Defaulted - not archived due to project not supplying data"),
                                       ("NotArchived", "Not going to archive - planned")))
    data_URL = models.URLField(blank=True, null=True)

    def __str__(self):
        return f"{self.title[:50]}"


class Note(models.Model):
    class Meta:
        verbose_name_plural = "Notes"
        ordering = ["added"]

    added = models.DateTimeField(auto_now_add=True)
    creator = models.ForeignKey(Person, null=True, blank=True, on_delete=models.PROTECT)
    notes = models.TextField(blank=True, null=True)

    content_type = models.ForeignKey(ContentType, null=True, blank=True, on_delete=models.PROTECT)
    object_id = PositiveIntegerField(null=True)
    location = GenericForeignKey('content_type', 'object_id')

dmp/forms.py
from django import forms
from .models import DataProduct, Project

class DateInput(forms.DateInput):
    input_type = 'date'

class DataProductForm(forms.ModelForm):
    class Meta:
        model = DataProduct
        fields = '__all__'
        widgets = {'deliverydate': DateInput()}


class ProjectForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = ('title', 'desc', 'PI', 'PIemail', 'desc', 'startdate', 'enddate', 'project_status', 'initial_contact',
                'dmp_agreed', 'sciSupContact', 'sciSupContact2', 'primary_dataCentre', 'other_dataCentres',
                'status', 'dmp_URL', 'ODMP_URL',)
        widgets = {'startdate': DateInput(), 'enddate': DateInput(), 'dmp_agreed': DateInput(), 'initial_contact': DateInput()}

dmp/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from .models import Project, DataProduct
from .forms import DataProductForm, ProjectForm
from django.db.models import Q
from django.urls import reverse



def project_list(request):
    user = request.user
    projects = Project.objects.filter(Q(grant__assigned_data_centre=user.data_centre) | Q(grant__other_data_centre=user.data_centre))
    return render(request, 'dmp/project_list.html', {'projects': projects})


@login_required
def project_detail(request, pk):
    project = get_object_or_404(Project, pk=pk)
    return render(request, 'dmp/project_detail.html', {'project': project})


@login_required
def dataproduct_new(request, project_id):
    project = get_object_or_404(Project, pk=project_id)
    if request.method == 'POST':
        form = DataProductForm(request.POST)
        if form.is_valid():
            dp = form.save(commit=False)
            dp.sciSupContact = request.user
            if not dp.sciSupContact:
                dp.sciSupContact = request.user
            if not dp.project:
                dp.project = project
            dp.save()
            return redirect(reverse('project_detail', kwargs={'pk': dp.project.pk}) + "#spaced-card")
    else:
        form = DataProductForm()
    return render(request, 'dmp/dataproduct_edit.html', {'form': form})


@login_required
def dataproduct_edit(request, pk, project_id):
    project = get_object_or_404(Project, pk=project_id)
    dataproduct = get_object_or_404(DataProduct, pk=pk)
    if request.method == "POST":
        form = DataProductForm(request.POST, instance=dataproduct)
        if form.is_valid():
            dp = form.save(commit=False)
            if not dp.sciSupContact:
                dp.sciSupContact = request.user
            if not dp.project:
                dp.project = project
            dp.save()
            return redirect(reverse('project_detail', kwargs={'pk': dp.project.pk}) + "#spaced-card")
    else:
        form = DataProductForm(instance=dataproduct)
    return render(request, 'dmp/dataproduct_edit.html', {'form': form, 'dataproduct': dataproduct})


@login_required
def dataproduct_delete(request, pk):
    dataproduct = get_object_or_404(DataProduct, pk=pk)
    if request.method == 'POST':
        dataproduct.delete()
        return redirect(reverse('project_detail', kwargs={'pk': dataproduct.project.pk}) + "#spaced-card")
    return render(request, 'dmp/dataproduct_edit.html', {'dataproduct': dataproduct})


def dataproduct_detail(request, pk):
    dataproduct = get_object_or_404(DataProduct, pk=pk)
    return render(request, 'dmp/dataproduct_detail.html', {'dataproduct': dataproduct})


@login_required
def project_edit(request, pk):
    project = get_object_or_404(Project, pk=pk)
    if request.method == "POST":
        form = ProjectForm(request.POST, instance=project)
        if form.is_valid():
            p = form.save(commit=False)
            p.primary_dataCentre = request.user.data_centre
            p.save()
            return redirect('project_detail', pk=p.pk)
    else:
        form = ProjectForm(instance=project)
    return render(request, 'dmp/project_edit.html', {'form': form, 'project':project})

dmp/templates/dmp/dataproduct_detail.html
{%  extends 'datamad2/base.html' %}
{% load staticfiles cookielaw_tags i18n fwtheme_tags %}
{% is_container_fluid as container_fluid %}

{% block content %}
    {% block page_special %}
    {% endblock %}

    {# To make content occupy full width, override the block page_container #}
    {# with one of the same name which OMITS the div class=container tag #}

    {% block page_container %}

        <div class="container{% if container_fluid %}-fluid{% endif %}">

        {% block content_main %}
            {% block content_header %}

                <div class="page-header" id="banner">
                <div class="row">
                <div class="col-lg-2 col-md-2 col-sm-2">
                    {% block page_title %}
                        <div class="wrapper">
                            <!-- Sidebar -->
                            <nav id="sidebar">
                            </nav>
                        </div>
                    {% endblock %}
                </div>
                <div class="col-lg-8">
                    <div class="w3-card">
                        <table  id="grants" style="width:100%">
                                <h3 id="title-detail">{{ dataproduct.title }} </h3>
                            <tr>
                                <th>Description</th>
                                <td class="column-id" > {{ dataproduct.desc }} </td>
                            </tr>

                            <tr>
                                <th>Data Volume</th>
                                <td class="column-id" >{{ dataproduct.datavol }} </td>
                            </tr>
                            <tr>
                                <th>Project</th>
                                <td class="column-id"  >{{ dataproduct.project }} </td>
                            </tr>
                            <tr>
                                <th>SciSupContact</th>
                                <td class="column-id" >{{ dataproduct.sciSupContact }} </td>
                            </tr>
                            <tr>
                                <th>Contact 1</th>
                                <td class="column-id" >{{ dataproduct.contact1 }} </td>
                            </tr>
                            <tr>
                                <th>Contact 2</th>
                                <td class="column-id">{{ dataproduct.contact2 }} </td>
                            </tr>
                            <tr>
                                <th>Delivery Date</th>
                                <td class="column-id">{{ dataproduct.deliverydate }} </td>
                            </tr>
                            <tr>
                                <th>Preservation Plan </th>
                                <td class="column-id" >{{ dataproduct.preservation_plan }} </td>
                            </tr>
                            <tr>
                                <th>Added</th>
                                <td class="column-id" >{{ dataproduct.added }} </td>
                            </tr>
                            <tr>
                                <th>Modified</th>
                                <td class="column-id" >{{ dataproduct.modified }} </td>
                            </tr>
                            <tr>
                                <th>Review Date</th>
                                <td class="column-id" >{{ dataproduct.review_date }} </td>
                            </tr>
                            <tr>
                                <th>Status</th>
                                <td class="column-id" >{{ dataproduct.status }} </td>
                            </tr>
                            <tr>
                                <th>Data URL</th>
                                <td class="column-id" >{{ dataproduct.data_URL }} </td>
                            </tr>
                        </table>
                    </div>
                </div>


            {% endblock content_header %}
        {% endblock content_main %}

    </div>

    {% endblock page_container %}
{%  endblock %}

</div>
</div>

dmp/templates/dmp/dataproduct_edit.html
{%  extends 'datamad2/base.html' %}
{% load staticfiles cookielaw_tags i18n fwtheme_tags %}
{% load lead_grant  %}
{% is_container_fluid as container_fluid %}

{%  block content %}
    {% block page_special %}
    {% endblock %}

    {% block head_js_extra %}
    {% endblock head_js_extra %}

    {# To make content occupy full width, override the block page_container #}
    {# with one of the same name which OMITS the div class=container tag #}

    {% block page_container %}

        <div class="container{% if container_fluid %}-fluid{% endif %}">

            {% block content_main %}
                {% block content_header %}

                    <div class="page-header" id="banner">
                    <div class="row">
                    <div class="col-lg-2 col-md-2 col-sm-2">
                    {% block page_title %}
                        <div class="wrapper">
                        <!-- Sidebar -->
                        <nav id="sidebar">
                        <div class="sidebar-header">
                        </div>
                        <ul class="list-unstyled components">
                        </ul>
                        </nav>
                        </div>
                    {% endblock %}
                    </div>
                    <div class="col">
                        <h3>New Data Product</h3>
                    <table>
                        <form method="POST">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-primary" id="claim">Save</button>
                        </form>
                        {%  if dataproduct.pk %}
                        <form action="{%  url 'dataproduct_delete' pk=dataproduct.pk %}" method="post">
                            {% csrf_token %}
                        <button type="submit" class="btn btn-primary" id="claim">Delete</button>
                        {%  endif %}
                        </form>
                    </table>
                    </div>

                {% endblock content_header %}
            {% endblock content_main %}
            </div>
            </div>
        </div>
    {% endblock page_container %}
{%  endblock %}

dmp/templates/dmp/project_detail.html
{%  extends 'datamad2/base.html' %}
{% load staticfiles cookielaw_tags i18n fwtheme_tags %}
{% is_container_fluid as container_fluid %}
{% load lead_grant  %}


{% block content %}
    {% block page_special %}
    {% endblock %}

    {# To make content occupy full width, override the block page_container #}
    {# with one of the same name which OMITS the div class=container tag #}

    {% block page_container %}

              <div class="container{% if container_fluid %}-fluid{% endif %}">

            {% block content_main %}
                {% block content_header %}

                    <div class="page-header" id="banner">
                    <div class="row">
                    <div class="col-lg-2 col-md-2 col-sm-2">
                    {% block page_title %}
                        <div class="wrapper">
                        <!-- Sidebar -->
                        <nav id="sidebar">
                        <div class="sidebar-header">
{#                            <h3>DMP</h3>#}
                        </div>
                        <ul class="list-unstyled components">
{#                        <h4>Projects</h4>#}
                        </ul>
                        </nav>
                        </div>
                    {% endblock %}
                </div>
                <div class="col-lg-8">
                <div>
                {%  for grant in project.grant_set.all %}
                    {% if grant|lead %}
                        <a href="{%  url 'grant_detail' pk=grant.importedgrant_set.first.pk  %}">
                        <button title='Lead Grant' data-toggle='tooltip' class="btn btn-primary claim-btn" id="grant-button-lead"> {{ grant.grant_ref }} </button>
                        </a>
                    {%  else %}
                        <a href="{%  url 'grant_detail' pk=grant.importedgrant_set.first.pk  %}">
                        <button class="btn btn-primary claim-btn" id="grant-button"> {{ grant.grant_ref }} </button>
                        </a>
                    {%  endif %}
                {%  endfor %}
                </div>
                    <div class="w3-card">
                        <table  id="grants" style="width:100%">
                            <h3 id="title-detail">
                                {{ project.title }}
                            <a title='Edit Project' data-toggle='tooltip' href="{% url 'project_edit' pk=project.pk %}"><i class="far fa-edit" id="edit"></i></a>
                            </h3>

                            <tr>
                                <th>PI</th>
                                <td class="column-id" > {{ project.PI }} </td>
                            </tr>

                            <tr>
                                <th>PI email</th>
                                <td class="column-id" >{{ project.PIemail }} </td>
                            </tr>
                            <tr>
                                <th>Description</th>
                                <td class="column-id"  >{{ project.desc }} </td>
                            </tr>
                            <tr>
                                <th>Start Date</th>
                                <td class="column-id" > {{ project.startdate }} </td>
                            </tr>
                            <tr>
                                <th>End Date</th>
                                <td class="column-id" >{{ project.enddate }} </td>
                            </tr>
                            <tr>
                                <th>Project Status</th>
                                <td class="column-id">{{ project.project_status }} </td>
                            </tr>
                            <tr>
                                <th>Initial Contact </th>
                                <td class="column-id">{{ project.initial_contact }} </td>
                            </tr>
                            <tr>
                                <th>DMP Agreed on</th>
                                <td class="column-id" >{{ project.dmp_agreed }} </td>
                            </tr>
                            <tr>
                                <th>SciSupContact</th>
                                <td class="column-id" >{{ project.sciSupContact }} </td>
                            </tr>
                            <tr>
                                <th>SciSupContact2</th>
                                <td class="column-id" >{{ project.sciSupContact2 }} </td>
                            </tr>
                            <tr>
                                <th>Primary Data Centre</th>
                                <td class="column-id" >{{ project.primary_dataCentre }} </td>
                            </tr>
                            <tr>
                                <th>Other Data Centre</th>
                                <td class="column-id" >{{ project.other_dataCentres }} </td>
                            </tr>
                            <tr>
                                <th>Status</th>
                                <td class="column-id" >{{ project.status }} </td>
                            </tr>
                            <tr>
                                <th>DMP URL</th>
                                <td class="column-id" >{{ project.dmp_URL }} </td>
                            </tr>
                            <tr>
                                <th>ODMP URL</th>
                                <td class="column-id" >{{ project.ODMP_URL }} </td>
                            </tr>
                            <tr>
                                <th>Programme</th>
                                <td class="column-id" >{{ project.programme }} </td>
                            </tr>
                        </table>
                    </div>
                      <div class="w3-card" id="spaced-card">
                            <tr>
                                <table class="row-border" id="dataproduct" style="width:100%">
                                    <tr>
                                        <th>Data Product</th>
                                        <th>Contact</th>
                                        <th>Status</th>
                                        <th>Delivery Date</th>
                                        <td><a href="{%  url 'dataproduct_new' project_id=project.pk %}" title='Add data product' data-toggle='tooltip'><i class="fas fa-plus"></i></a></td>
                                    </tr>
                                    {%  for data_product in project.dataproduct_set.all %}
                                        <tr>
                                            <td>
                                            <a href="{%  url 'dataproduct_detail' pk=data_product.pk %}">
                                                {{  data_product.title }}
                                            </a>
                                            </td>
                                            <td> {{ data_product.contact }}</td>
                                            <td> {{  data_product.status }}</td>
                                            <td> {{ data_product.deliverydate }}</td>
                                            <td> <a title='Edit data product' data-toggle='tooltip' href="{% url 'dataproduct_edit' pk=data_product.pk project_id=project.pk %}"><i class="far fa-edit"></i></a></td>
                                        </tr>
                                    {%  endfor %}
                                </table>
                            </tr>
                        </div>
                </div>


            {% endblock content_header %}
        {% endblock content_main %}

    </div>

    {% endblock page_container %}
{%  endblock %}

dmp/templates/dmp/project_edit.html
{%  extends 'datamad2/base.html' %}
{% load staticfiles cookielaw_tags i18n fwtheme_tags %}
{% load lead_grant  %}
{% is_container_fluid as container_fluid %}

{%  block content %}
    {% block page_special %}
    {% endblock %}

    {% block head_js_extra %}
    {% endblock head_js_extra %}

    {# To make content occupy full width, override the block page_container #}
    {# with one of the same name which OMITS the div class=container tag #}

    {% block page_container %}

        <div class="container{% if container_fluid %}-fluid{% endif %}">

            {% block content_main %}
                {% block content_header %}

                    <div class="page-header" id="banner">
                    <div class="row">
                    <div class="col-lg-2 col-md-2 col-sm-2">
                        {% block page_title %}
                            <div class="wrapper">
                                <!-- Sidebar -->
                                <nav id="sidebar">
                                    <div class="sidebar-header">
                                    </div>
                                    <ul class="list-unstyled components">
                                    </ul>
                                </nav>
                            </div>
                        {% endblock %}
                    </div>
                    <div class="col">

                        <h4>Edit Project</h4>


                        <table>
                            <form method="POST">
                                {% csrf_token %}
                                {%  for field in form %}
                                    <tr class="fieldWrapper">
                                        <td>{{ field.errors }}</td>
                                        <td>{{ field.label_tag }}</td>
                                        <td> {{ field }}</td>
                                    </tr>
                                {% endfor %}

                        </table>
                        <button type="submit" class="btn btn-primary" id="delete">Save</button>
                        </form>
                    </div>

                {% endblock content_header %}
            {% endblock content_main %}
            </div>
            </div>
        </div>
    {% endblock page_container %}
{%  endblock %}